# Generated by Django 5.1.1 on 2025-10-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
        ('terms', '0002_drop_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['institute', 'start_date', 'end_date'], name='term_inst_dates_idx'),
        ),
    ]
