# Generated by Django 5.1.1 on 2025-11-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
        ('terms', '0004_termtransition'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowTermCountAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_alert_sent_at', models.DateTimeField(blank=True, help_text='When the last low term count alert was sent', null=True)),
                ('future_terms_count_at_last_alert', models.IntegerField(default=0, help_text='Number of future terms when last alert was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.OneToOneField(help_text='The institute this alert tracking belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='low_term_alert', to='institutes.institute')),
            ],
            options={
                'db_table': 'terms_low_term_alert',
                'indexes': [models.Index(fields=['institute', 'last_alert_sent_at'], name='term_alert_inst_sent_idx')],
            },
        ),
    ]
