# Generated by Django 5.1.1 on 2025-09-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeefunction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employeefunction',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute'),
        ),
        migrations.AddIndex(
            model_name='employeefunction',
            index=models.Index(condition=models.Q(('institute__isnull', True)), fields=['name'], name='empfunc_name_global_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefunction',
            index=models.Index(condition=models.Q(('institute__isnull', False)), fields=['institute', 'name'], name='empfunc_inst_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeefunction',
            constraint=models.UniqueConstraint(condition=models.Q(('institute__isnull', True)), fields=('name',), name='uq_empfunc_global_name'),
        ),
        migrations.AddConstraint(
            model_name='employeefunction',
            constraint=models.UniqueConstraint(condition=models.Q(('institute__isnull', False)), fields=('institute', 'name'), name='uq_empfunc_per_institute_name'),
        ),
    ]
