# Generated by Django 5.1.1 on 2025-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeefunction_unique_together_and_more'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeecareer',
            name='emp_career_idx',
        ),
        migrations.AddIndex(
            model_name='employeecareer',
            index=models.Index(fields=['employee', 'end_date'], name='emp_car_emp_end_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecareer',
            index=models.Index(fields=['function', 'end_date'], name='emp_car_fun_end_idx'),
        ),
    ]
