# Generated by Django 5.1.1 on 2025-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeecareer_emp_career_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefunction',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
