# Generated by Django 5.1.1 on 2025-10-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_net_salary_to_gross_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
