# Generated by Django 5.1.1 on 2025-10-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_effective_dated_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecareer',
            name='gross_salary_due',
        ),
    ]
