# Generated by Django 5.1.1 on 2025-10-31 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_employeecareer_gross_salary_due'),
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='epin',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('institute', 'epin'), name='uq_employee_epin_per_institute'),
        ),
    ]
