# Generated by Django 5.1.1 on 2025-11-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecareer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Employee who created this career assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_career_assignments', to='employees.employee'),
        ),
    ]
