# Generated by Django 5.1.1 on 2025-09-28 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('institute', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('spin', models.CharField(max_length=32, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Unspecified')], max_length=12, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Not married'), ('married', 'Married'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=12, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nationality', models.CharField(blank=True, max_length=60, null=True)),
                ('national_id', models.CharField(blank=True, max_length=64, null=True)),
                ('previous_institute', models.CharField(blank=True, max_length=160, null=True)),
                ('grade_acquired', models.CharField(blank=True, max_length=60, null=True)),
                ('district', models.CharField(blank=True, max_length=120, null=True)),
                ('county', models.CharField(blank=True, max_length=120, null=True)),
                ('sub_county_division', models.CharField(blank=True, max_length=120, null=True)),
                ('parish', models.CharField(blank=True, max_length=120, null=True)),
                ('cell_village', models.CharField(blank=True, max_length=120, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCustodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other/Unspecified')], max_length=12, null=True)),
                ('relation', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('sponsor', 'Sponsor')], max_length=20)),
                ('phone_number_1', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=40, null=True)),
                ('place_of_work', models.CharField(blank=True, max_length=160, null=True)),
                ('nationality', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('sub_country', models.CharField(blank=True, max_length=120, null=True)),
                ('parish', models.CharField(blank=True, max_length=120, null=True)),
                ('cell', models.CharField(blank=True, max_length=120, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodians', to='students.student')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enquire', 'Enquire'), ('accepted', 'Accepted'), ('no_show', 'No show'), ('active', 'Active'), ('retake', 'Retake'), ('failed', 'Failed'), ('graduate', 'Graduate'), ('drop_out', 'Drop out'), ('expelled', 'Expelled'), ('not_accepted', 'Not accepted')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courseclass')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='students.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicterm')),
            ],
            options={
                'ordering': ['-effective_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institute', 'last_name', 'first_name'], name='stu_inst_last_first_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['spin'], name='stu_spin_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('institute', 'first_name', 'last_name', 'date_of_birth'), name='uq_student_person_like'),
        ),
        migrations.AddIndex(
            model_name='studentcustodian',
            index=models.Index(fields=['student', 'relation'], name='cust_student_relation_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcustodian',
            index=models.Index(fields=['last_name', 'first_name'], name='cust_last_first_idx'),
        ),
        migrations.AddIndex(
            model_name='studentstatus',
            index=models.Index(fields=['student', '-effective_at'], name='status_student_eff_idx'),
        ),
        migrations.AddIndex(
            model_name='studentstatus',
            index=models.Index(fields=['term'], name='status_term_idx'),
        ),
        migrations.AddIndex(
            model_name='studentstatus',
            index=models.Index(fields=['course_class'], name='status_class_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('institute', 'student'), name='uq_one_active_status_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studentstatus',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['active', 'retake']), ('term__isnull', False)), models.Q(('status__in', ['active', 'retake']), _negated=True), _connector='OR'), name='ck_term_required_for_active_or_retake'),
        ),
    ]
