# Generated by Django 5.1.1 on 2025-10-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentstatus_term_delete_academicterm copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
