# Generated by Django 5.1.1 on 2025-10-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseclass_start_date_and_more'),
        ('institutes', '0001_initial'),
        ('students', '0004_student_bank_account_number_student_bank_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentstatus',
            name='uq_one_active_status_per_student',
        ),
        migrations.RemoveConstraint(
            model_name='studentstatus',
            name='ck_term_required_for_active_or_retake',
        ),
        migrations.RemoveIndex(
            model_name='studentstatus',
            name='status_student_eff_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentstatus',
            name='status_term_idx',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='term',
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='course_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='courses.courseclass'),
        ),
        migrations.AddIndex(
            model_name='studentstatus',
            index=models.Index(fields=['student', 'course_class', '-effective_at'], name='status_student_class_eff_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('institute', 'student', 'course_class'), name='uq_one_active_status_per_student_per_class'),
        ),
        migrations.AddConstraint(
            model_name='studentstatus',
            constraint=models.CheckConstraint(condition=models.Q(('course_class__isnull', False)), name='ck_class_required_for_progress'),
        ),
        migrations.AddConstraint(
            model_name='studentstatus',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'retake', 'failed', 'graduate', 'drop_out', 'expelled'])), name='ck_status_is_progression'),
        ),
    ]
