# Generated by Django 5.1.1 on 2025-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
        ('students', '0005_remove_studentstatus_uq_one_active_status_per_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spin',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('institute', 'spin'), name='uq_student_spin_per_institute'),
        ),
    ]
