# Generated by Django 5.1.1 on 2025-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_courseclass_start_date_and_more"),
        ("institutes", "0001_initial"),
        ("students", "0007_alter_student_gender_alter_studentcustodian_gender"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studentstatus",
            name="ck_status_is_progression",
        ),
        migrations.AlterField(
            model_name="studentstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("enquire", "Enquire"),
                    ("accepted", "Accepted"),
                    ("not_accepted", "Not accepted"),
                    ("no_show", "No show"),
                    ("active", "Active"),
                    ("retake", "Retake"),
                    ("failed", "Failed"),
                    ("graduate", "Graduate"),
                    ("drop_out", "Drop out"),
                    ("expelled", "Expelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="studentstatus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "enquire",
                            "accepted",
                            "not_accepted",
                            "no_show",
                            "active",
                            "retake",
                            "failed",
                            "graduate",
                            "drop_out",
                            "expelled",
                        ],
                    )
                ),
                name="ck_status_is_valid",
            ),
        ),
    ]
