# Generated by Django 5.1.1 on 2025-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_studentstatus_ck_status_is_progression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
