# Generated by Django 5.1.1 on 2025-11-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_updated_at'),
        ('students', '0009_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Employee who created this status change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_statuses', to='employees.employee'),
        ),
    ]
