# Generated by Django 5.1.1 on 2025-10-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('E', 'Employee'), ('S', 'Student')], max_length=1)),
                ('year2', models.PositiveSmallIntegerField()),
                ('term_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_no', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institute', 'kind', 'year2', 'term_no'), name='uniq_pin_scope')],
            },
        ),
    ]
