# Generated by Django 5.1.1 on 2025-09-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('acc_category', models.CharField(max_length=128, unique=True)),
                ('section', models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('LFB', 'Liquid funds - Banks')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['acc_category'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CASHBOX', 'Cashbox'), ('BANK', 'Bank')], max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('counterparty', models.CharField(blank=True, max_length=256)),
                ('comment', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financeaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.accounttype')),
                ('credit_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='finance.accounttype')),
                ('credit_finance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='finance.financeaccount')),
                ('debit_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='finance.accounttype')),
                ('debit_finance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='finance.financeaccount')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
            ],
            options={
                'db_table': 'finance_ledger_entry',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='financeaccount',
            index=models.Index(fields=['institute', 'kind'], name='finance_fin_institu_0bd62b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financeaccount',
            unique_together={('institute', 'name')},
        ),
        migrations.AddIndex(
            model_name='financeledgerentry',
            index=models.Index(fields=['institute', 'date'], name='finance_led_institu_7ccb32_idx'),
        ),
        migrations.AddIndex(
            model_name='financeledgerentry',
            index=models.Index(fields=['institute', 'account', 'date'], name='finance_led_institu_75a679_idx'),
        ),
        migrations.AddIndex(
            model_name='financeledgerentry',
            index=models.Index(fields=['transfer_id'], name='finance_led_transfe_ee0c8e_idx'),
        ),
    ]
