# Generated by Django 5.1.1 on 2025-09-22 11:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('acc_category', models.CharField(max_length=128, unique=True)),
                ('section', models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('LFB', 'Liquid funds - Banks')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['acc_category'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CASHBOX', 'Cashbox'), ('BANK', 'Bank')], max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('counterparty', models.CharField(blank=True, max_length=256)),
                ('comment', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financeaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.accounttype')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='financeaccount',
            index=models.Index(fields=['institute_id', 'kind'], name='finance_fin_institu_0bd62b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financeaccount',
            unique_together={('institute_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='financeledgerentry',
            index=models.Index(fields=['institute_id', 'date'], name='finance_fin_institu_37e070_idx'),
        ),
        migrations.AddIndex(
            model_name='financeledgerentry',
            index=models.Index(fields=['institute_id', 'account', 'date'], name='finance_fin_institu_74cb15_idx'),
        ),
        migrations.AddIndex(
            model_name='financeledgerentry',
            index=models.Index(fields=['transfer_id'], name='finance_fin_transfe_c1e351_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount', Decimal('0.00')), _negated=True), name='ledger_amount_nonzero'),
        ),
    ]
