# Generated by Django 5.1.1 on 2025-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financeaccount',
            name='finance_fin_institu_0bd62b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='financeaccount',
            unique_together={('institute', 'name')},
        ),
        migrations.AddIndex(
            model_name='financeaccount',
            index=models.Index(fields=['institute', 'kind'], name='finance_fin_institu_0bd62b_idx'),
        ),
    ]
