# Generated by Django 5.1.1 on 2025-09-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_financeaccount_finance_fin_institu_0bd62b_idx_and_more'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financeledgerentry',
            name='finance_fin_institu_37e070_idx',
        ),
        migrations.RemoveIndex(
            model_name='financeledgerentry',
            name='finance_fin_institu_74cb15_idx',
        ),
        migrations.AddIndex(
            model_name='financeledgerentry',
            index=models.Index(fields=['institute', 'date'], name='finance_fin_institu_37e070_idx'),
        ),
        migrations.AddIndex(
            model_name='financeledgerentry',
            index=models.Index(fields=['institute', 'account', 'date'], name='finance_fin_institu_74cb15_idx'),
        ),
    ]
