# Generated by Django 5.1.1 on 2025-09-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_financeledgerentry_finance_fin_institu_37e070_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financeledgerentry',
            name='ledger_amount_nonzero',
        ),
        migrations.RenameIndex(
            model_name='financeledgerentry',
            new_name='finance_led_institu_7ccb32_idx',
            old_name='finance_fin_institu_37e070_idx',
        ),
        migrations.RenameIndex(
            model_name='financeledgerentry',
            new_name='finance_led_institu_75a679_idx',
            old_name='finance_fin_institu_74cb15_idx',
        ),
        migrations.RenameIndex(
            model_name='financeledgerentry',
            new_name='finance_led_transfe_ee0c8e_idx',
            old_name='finance_fin_transfe_c1e351_idx',
        ),
        migrations.AddField(
            model_name='financeledgerentry',
            name='credit_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='finance.accounttype'),
        ),
        migrations.AddField(
            model_name='financeledgerentry',
            name='credit_finance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='financeledgerentry',
            name='debit_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='finance.accounttype'),
        ),
        migrations.AddField(
            model_name='financeledgerentry',
            name='debit_finance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='finance.financeaccount'),
        ),
        migrations.AlterField(
            model_name='financeledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='financeledgerentry',
            name='created_by_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterModelTable(
            name='financeledgerentry',
            table='finance_ledger_entry',
        ),
    ]
