# Generated by Django 5.1.1 on 2025-08-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('spin', models.CharField(max_length=32, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institute', 'first_name', 'last_name', 'date_of_birth'), name='uq_student_person_like')],
            },
        ),
    ]
