# Generated by Django 5.1.1 on 2025-08-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_term_studentcustodian_studentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstatus',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='term',
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='term',
            name='institute',
        ),
        migrations.DeleteModel(
            name='StudentCustodian',
        ),
        migrations.DeleteModel(
            name='StudentStatus',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
