# Generated by Django 5.1.1 on 2025-09-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0001_initial"),
        ("students", "0004_term_studentcustodian_studentstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="cell_village",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="student",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="county",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="student",
            name="district",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="entry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="exit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other / Unspecified"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="grade_acquired",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="student",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Not married"),
                    ("married", "Married"),
                    ("separated", "Separated"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="national_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="student",
            name="nationality",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="student",
            name="parish",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_institute",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="student",
            name="sub_county_division",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="studentstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("enquire", "Enquire"),
                    ("accepted", "Accepted"),
                    ("no_show", "No show"),
                    ("active", "Active"),
                    ("retake", "Retake"),
                    ("failed", "Failed"),
                    ("graduate", "Graduate"),
                    ("drop_out", "Drop out"),
                    ("expelled", "Expelled"),
                    ("not_accepted", "Not accepted"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["institute", "last_name", "first_name"],
                name="students_st_institu_b25af1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["spin"], name="students_st_spin_aafc8f_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("institute", "student"),
                name="uq_one_active_status_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentstatus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["active", "retake"]), ("term__isnull", False)
                    ),
                    models.Q(("status__in", ["active", "retake"]), _negated=True),
                    _connector="OR",
                ),
                name="ck_term_required_for_active_or_retake",
            ),
        ),
    ]
