# Generated by Django 5.1.1 on 2025-09-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0005_student_cell_village_student_comments_student_county_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cell_village",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="county",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="district",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other / Unspecified"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade_acquired",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Not married"),
                    ("married", "Married"),
                    ("separated", "Separated"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="national_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="nationality",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="parish",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="previous_institute",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="sub_county_division",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
