# Generated by Django 5.1.1 on 2025-09-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('employees', '0001_initial'),
        ('institutes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='courses.courseclass'),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaches_classes', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.courseclass'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('institute', 'abbr_name'), ('institute', 'name')},
        ),
        migrations.AddIndex(
            model_name='courseclass',
            index=models.Index(fields=['term'], name='courseclass_term_idx'),
        ),
        migrations.AddIndex(
            model_name='courseclass',
            index=models.Index(fields=['institute', 'term'], name='courseclass_inst_term_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseclass',
            unique_together={('institute', 'course', 'class_number', 'term')},
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['course_class'], name='ci_class_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['institute', 'course_class'], name='ci_inst_class_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseinstructor',
            unique_together={('institute', 'course_class', 'instructor')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course_class'], name='enr_student_class_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('institute', 'student', 'course_class')},
        ),
    ]
