# Generated by Django 5.1.1 on 2025-10-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='weekly_lessons_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
