# Generated by Django 5.1.1 on 2025-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseclass_created_at_courseclass_updated_at_and_more'),
        ('employees', '0004_employeefunction_code'),
        ('institutes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseclass',
            index=models.Index(fields=['term'], name='courseclass_term_idx'),
        ),
        migrations.AddIndex(
            model_name='courseclass',
            index=models.Index(fields=['institute', 'term'], name='courseclass_inst_term_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['institute', 'course_class'], name='ci_inst_class_idx'),
        ),
    ]
