# Generated by Django 5.1.1 on 2025-10-28 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_weekly_lessons_text'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseclass',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='courseclass',
            name='courseclass_term_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseclass',
            name='courseclass_inst_term_idx',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='courseclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='total_classes',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='hours_per_term',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='index',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutes.institute'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='course',
            name='abbr_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classes_total',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hours_per_term',
        ),
        migrations.RemoveField(
            model_name='course',
            name='outcomes_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prior_knowledge_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='required_skills_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='course',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='course',
            name='weekly_lessons_text',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='term',
        ),
    ]
