# Generated by Django 5.1.1 on 2025-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options_alter_courseclass_options_and_more'),
        ('employees', '0004_employee_photo'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courseinstructor',
            name='ci_class_idx',
        ),
        migrations.RenameIndex(
            model_name='courseinstructor',
            new_name='courses_cou_institu_d974af_idx',
            old_name='ci_inst_class_idx',
        ),
        migrations.AlterUniqueTogether(
            name='courseinstructor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(fields=('course_class', 'instructor'), name='uq_course_class_instructor'),
        ),
    ]
