# Generated by Django 5.1.1 on 2025-10-29 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_courseinstructor_ci_class_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'index'), name='uq_courseclass_course_index'),
        ),
    ]
