# Generated by Django 5.1.1 on 2025-11-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseclass_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
