# Generated by Django 5.1.1 on 2025-11-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_valid_from_course_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='learning_outcomes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='required_knowledge',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='required_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='weekly_lessons',
            field=models.TextField(blank=True, default=''),
        ),
    ]
