# Generated by Django 5.1.1 on 2025-11-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courseclass_learning_outcomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='required_knowledge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='weekly_lessons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
