# Generated by Django 5.1.1 on 2025-11-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courseclass_learning_outcomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
